interface EditorConfig {
  id: string;
  name: string;
  icon: string;
  description: string;
  usageGuide: string[];
}

export const EDITORS: EditorConfig[] = [
  {
    id: 'vscode',
    name: 'VS Code',
    icon: '📝',
    description: 'Visual Studio Code with GitHub Copilot',
    usageGuide: [
      '1. Open VS Code Settings (Ctrl+, or Cmd+,)',
      '2. Search for "Copilot: Instructions"',
      '3. Paste the downloaded .md file content',
      '4. Save and restart VS Code',
      '5. Use with Copilot Chat (Ctrl+Shift+I)',
    ],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    icon: '✨',
    description: 'Cursor IDE with built-in AI',
    usageGuide: [
      '1. Open Cursor Settings (Ctrl+, or Cmd+,)',
      '2. Search for "Custom Instructions"',
      '3. Paste the downloaded .md file content',
      '4. Save settings',
      '5. Start using with Cursor Chat (Ctrl+K)',
    ],
  },
  {
    id: 'kiro',
    name: 'Kiro',
    icon: '🚀',
    description: 'Kiro AI Code Editor',
    usageGuide: [
      '1. Open Kiro Editor and go to Preferences',
      '2. Find "Agent Instructions" or "Custom Prompts"',
      '3. Paste the downloaded .md file content',
      '4. Click Save and Apply',
      '5. Your agent is ready to use',
    ],
  },
  {
    id: 'antigravity',
    name: 'Antigravity',
    icon: '🌌',
    description: 'Antigravity AI Development Platform',
    usageGuide: [
      '1. Log into your Antigravity workspace',
      '2. Go to Settings → Add New Agent',
      '3. Upload or paste the downloaded .md file',
      '4. Configure agent settings if needed',
      '5. Save and activate the agent',
    ],
  },
  {
    id: 'other',
    name: 'Other Editors',
    icon: '🛠️',
    description: 'ChatGPT, Gemini, or other AI platforms',
    usageGuide: [
      '1. Open your AI platform (ChatGPT, Gemini, etc.)',
      '2. Start a new conversation',
      '3. Copy the downloaded .md file content',
      '4. Paste it at the beginning of your message',
      '5. Send and use your agent',
    ],
  },
      '',
      'Method 3: .github/copilot-instructions.md (Repository Level)',
      '• Create folder: .github (if it doesn\'t exist)',
      '• Place your .md file as: .github/copilot-instructions.md',
      '• Push to GitHub and configure in Copilot settings',
      '',
      'Verification:',
      '• Restart VS Code or reload window (Ctrl+Shift+P → "Developer: Reload Window")',
      '• Copilot Chat will now reference your custom instructions',
    ],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    icon: '✨',
    description: 'Cursor IDE - VS Code fork with AI superpowers',
    usageGuide: [
      'Setup Instructions for Cursor IDE:',
      '',
      'Method 1: Global Custom Instructions (Recommended)',
      '• Click the Settings icon in the bottom-left corner of Cursor',
      '• Go to "Cursor Settings" → "Features" → "Cursor Tab"',
      '• Scroll down to "Cursor Instructions"',
      '• Paste the full content from your downloaded .md file',
      '• These instructions apply to all conversations in Cursor globally',
      '',
      'Method 2: .cursor/instructions.txt File',
      '• Create folder: .cursor (in your project root or home directory)',
      '• Create file: instructions.txt',
      '• Copy the content from your downloaded .md file (paste just the prompt content, not the frontmatter)',
      '• Cursor will automatically read this file for instructions',
      '',
      'Method 3: Workspace-Level Rules',
      '• Place your .md file in project root as ".cursorrules"',
      '• Cursor will apply these rules to the current workspace',
      '• Share this file with your team by committing to git',
      '',
      'Verification:',
      '• Restart Cursor or reload the window',
      '• Open Cursor Chat (Cmd+K or Ctrl+K)',
      '• Your custom instructions are now active',
    ],
  },
  {
    id: 'cody',
    name: 'Cody',
    icon: '🔍',
    description: 'Sourcegraph Cody - Context-aware AI assistant with code search',
    usageGuide: [
      'Setup Instructions for Cody:',
      '',
      'Method 1: Custom Commands (Recommended)',
      '• Install Cody extension in VS Code or JetBrains IDE',
      '• Open Cody settings (via the Cody icon in sidebar)',
      '• Navigate to "Manage Custom Commands"',
      '• Click "Create Custom Command"',
      '• Paste your downloaded .md file content as the command definition',
      '• Save with an appropriate name (e.g., "Agent: MyAgentName")',
      '• This custom command is now available globally in your IDE',
      '',
      'Method 2: .cody Configuration',
      '• Create file: .cody.yaml in your project root',
      '• Add your agent instructions to the custom context section',
      '• Cody will load these automatically for all conversations in this project',
      '',
      'Method 3: User Settings (IDE-Level)',
      '• VS Code: Open Command Palette → "Preferences: Open Settings (JSON)"',
      '• Add Cody configuration with your custom instructions',
      '• Apply globally across all VS Code workspaces',
      '',
      'Usage:',
      '• Once configured, invoke your custom command from Cody Chat',
      '• Select it from the available commands in the chat interface',
    ],
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    icon: '🌊',
    description: 'Windsurf by Codeium - AI-first IDE with deep code integration',
    usageGuide: [
      'Setup Instructions for Windsurf:',
      '',
      'Method 1: .windsurf (Agent Files - Recommended)',
      '• Create folder: .windsurf (in your project root)',
      '• Create file: agent.md inside .windsurf folder',
      '• Copy your downloaded .md file content into agent.md',
      '• Windsurf automatically loads and applies these agent instructions',
      '• Share the .windsurf folder with your team via git',
      '',
      'Method 2: Global Windsurf Profile',
      '• Open Windsurf Settings (Ctrl+,)',
      '• Search for "Agent" or "Custom Instructions"',
      '• Add your agent prompt content to the global settings',
      '• Applies to all projects opened in Windsurf',
      '',
      'Method 3: Project Rules',
      '• Create file: windsurf.rules in project root',
      '• Add your agent instructions and formatting rules',
      '• Windsurf loads these automatically for the project',
      '',
      'Verification:',
      '• Open Windsurf Chat panel (Cmd+K or Ctrl+K)',
      '• Your agent instructions are now active globally',
      '• Windsurf will follow these rules for all file suggestions and edits',
    ],
  },
  {
    id: 'other',
    name: 'Other',
    icon: '🛠️',
    description: 'Any AI tool or custom setup',
    usageGuide: [
      'Generic Setup Instructions for Global AI Prompts:',
      '',
      'For Most Code Editors:',
      '• Look for "Settings" or "Preferences" in your editor',
      '• Search for keywords: "Custom Instructions", "Agent", "Prompts", "Context"',
      '• Create a new custom instruction/prompt entry',
      '• Paste your downloaded .md file content',
      '• Save and restart the editor',
      '',
      'For Chat-Based AI Services (ChatGPT, Gemini, Copilot Chat):',
      '• These often support "Custom Instructions" or "System Prompts"',
      '• Go to your profile settings or preferences',
      '• Find the "Custom Instructions" section',
      '• Add the content from your downloaded .md file',
      '• These will apply to all conversations in that service',
      '',
      'For Local Setups:',
      '• If using local LLM tools (Ollama, LM Studio, etc.)',
      '• Place your .md file in the system prompts directory',
      '• Configure your tool to use this custom system prompt',
      '• Restart your local service',
      '',
      'Best Practice:',
      '• Store your agent files in version control (.git)',
      '• Use filenames like ".instructions.md" or ".agent.md"',
      '• This makes setup repeatable across teams and machines',
    ],
  },
];

export function getEditorConfig(id: string): EditorConfig | undefined {
  return EDITORS.find((editor) => editor.id === id);
}

